# Generated by Django 4.2.1 on 2023-05-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=100, verbose_name='Адрес места жительства')),
                ('education', models.CharField(blank=True, max_length=100, null=True, verbose_name='Образование')),
                ('workplace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('children', models.TextField(blank=True, max_length=255, null=True, verbose_name='Семейное положение, дети')),
                ('life_events', models.TextField(blank=True, max_length=255, null=True, verbose_name='Жизненные события клиента')),
                ('illnesses', models.TextField(blank=True, null=True, verbose_name='Заболевания, жалобы клиента')),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диагноз')),
                ('last_consultation_date', models.DateField(blank=True, null=True, verbose_name='Дата последней консультации')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/photos')),
            ],
        ),
    ]
